# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='agent',
            new_name='house_agent',
        ),
    ]
