# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='selling',
            field=models.BooleanField(default=True),
        ),
    ]
