# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_auto_20160913_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='neighborhood',
            new_name='house_neighborhood',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='house',
            new_name='owner_house',
        ),
    ]
