# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20160916_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='last_sold',
            field=models.DateField(null=True),
        ),
    ]
