# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0006_auto_20160917_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
