# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0007_auto_20160919_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_agent', to='neighborhood.Agent'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_buyer', to='neighborhood.Buyer'),
        ),
    ]
