# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0008_auto_20160920_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
