# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0009_auto_20160920_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('sale_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sale', to='neighborhood.Agent')),
                ('sale_buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sale', to='neighborhood.Buyer')),
                ('sale_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sale', to='neighborhood.House')),
                ('sale_neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sale', to='neighborhood.Neighborhood')),
            ],
        ),
    ]
