# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0011_auto_20160921_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user_type',
            field=models.CharField(default='agent', max_length=5),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user_type',
            field=models.CharField(default='buyer', max_length=5),
        ),
    ]
