# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0012_auto_20160921_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convo_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo', to='neighborhood.Agent')),
                ('convo_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo', to='neighborhood.Buyer')),
                ('convo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo', to='neighborhood.HouseRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('recipient', models.CharField(max_length=200)),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='neighborhood.Conversation')),
            ],
        ),
    ]
